### ISSUE TITLE
使用饿了么组件报错

### ISSUE THREAD

**Issue by showzyl** [lzxb/vue2-demo#1]
http://mint-ui.github.io/docs/#!/zh-cn2

我使用以上组件，按照文档的步骤能够跑起来项目，单独跑你的项目也能ok，我想结合一下，
在.babelrc 里 增加了 { "modules": false }  
"plugins": [["component", [
    {
      "libraryName": "mint-ui",
      "style": true
    }
  ]]]

然后就报错了，麻烦能指点一下么？

**Comment by lzxb** [comment]
具体是报什么错误

**Comment by showzyl** [comment]
ERROR in ./src/main.js
Module not found: Error: Cannot resolve module 'mint-ui/style.css' in /Users/showzyl/Desktop/test/vue2-demo/src
 @ ./src/main.js 3:13-41

ERROR in   Error: Child compilation failed:
  Module build failed: TypeError: /Users/showzyl/Desktop/test/vue2-demo/node_modules/lodash/lodash.js: Cannot read property 'name' of n  ull

main.js 里`import 'mint-ui/style.css'` 无法编译通过，不太明白这个是为什么造成的。

**Comment by lzxb** [comment]
找不到这个文件

**Comment by noikiy** [comment]
可以这样处理
`
  "plugins": ["transform-runtime", ["component", [{
    "libraryName": "mint-ui",
    "style": "lib/style.css"
  }]]],
`

**Comment by lzxb** [comment]
下次我也试试
