### ISSUE TITLE
可以解释一下vue2-demo/src/config/routes.js里面的resolve方法做什么的吗？

### ISSUE THREAD

**Issue by slimeball** [lzxb/vue2-demo#10]
component: **resolve => require(['../pages/login/'], resolve)**

**Comment by lzxb** [comment]
异步加载模块，也就是说用户首次访问这个页面的时候，去下载这个页面的代码，然后再进行渲染出来

**Comment by fandudu** [comment]
请问里面的默认路由是怎么实现的

**Comment by lzxb** [comment]
* 号类匹配就可以了，放在最好

**Comment by fandudu** [comment]
![image](https://cloud.githubusercontent.com/assets/15722726/23936773/df3d20ba-098e-11e7-9ff0-421efc2749f2.png)
这是我的东西，帮看一下为什么默认不是第一个路由呢

**Comment by lzxb** [comment]
路由能匹配上吗？具体是跳转到了什么地址？有可能是父级没有/导致的

**Comment by fandudu** [comment]
我看看把3q
