### ISSUE TITLE
resolve函数在哪里啊？

### ISSUE THREAD

**Issue by candy1919** [lzxb/vue2-demo#12]
component: resolve => require(['../pages/login/'], resolve)这里的resolve函数在哪？

**Comment by candy1919** [comment]
是vue-router的懒加载的内容= =

**Comment by zhoupeihuang** [comment]
好像项目被 cnodejs.org 给劫持了，打开就是那个官网里面的内容，

**Comment by zhoupeihuang** [comment]
项目启动就有这个
[HPM] Proxy created: **  ->  https://cnodejs.org/
