### ISSUE TITLE
请问 这个问题是怎么回事？

### ISSUE THREAD

**Issue by altlantis** [lzxb/vue2-demo#13]
These relative modules were not found:

* ./config/routes in ./src/main.js
* ./assets/logo.png in ./~/._vue-loader@11.3.4@vue-loader/lib/template-compiler?{"id":"data-v-2a38d292"}!./~/._vue-loader@11.3.4@vue-loader/lib/selector.js?type=template&index=0!./src/App.vue
> Listening at http://localhost:8080
3000那个也不能访问呢。

**Comment by lzxb** [comment]
没有找到模块
