### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by altlantis** [lzxb/vue2-demo#15]
我想了很久实在不明白
为什么component里的header.vue不是已经export default了么  为什么还要单独创建一个index,js来export default一遍呢？  关键是我把这个index.js删除了还不行。。。

**Comment by lzxb** [comment]
这是为了将components目录下的组件，全部安装到vue的全局组件中去

**Comment by altlantis** [comment]
components下面的组件 不就是只有一个公共组件header吗？

**Comment by lzxb** [comment]
以后随着项目的需要，会不断添加进去啊
