### ISSUE TITLE
关于用户登录退出的问题

### ISSUE THREAD

**Issue by AC-YoY** [lzxb/vue2-demo#16]
我尝试使用了一下这个登录模块，碰到了一个问题：

目前的登录和退出是由vuex中的状态来控制的，
0. 登录时添加状态，
1. 路由切换时通过钩子检查该状态是否存在，

但是这样有一个问题，无论当前的URL在哪，只要刷新页面，vuex被清空，用户就一定会退出。
这是确实存在的问题，还是我漏了什么关键部分？

我的解决办法是将状态保存了一份在session/localStorage中，路由切换时检查，
可是这样一来，原本vuex的状态就变得非常鸡肋。

望赐教

**Comment by lzxb** [comment]
是要这样实现的。vuex只是将状态存储在内存里面

**Comment by AC-YoY** [comment]
谢谢解答
