### ISSUE TITLE
希望楼主能看看为什么回跳到node社区页

### ISSUE THREAD

**Issue by 5265liu** [lzxb/vue2-demo#17]
看评论应该有好几个人都遇到这个问题了

**Comment by lzxb** [comment]
从哪里跳回node社区首页？
请把问题描述得更清楚一些

**Comment by 5265liu** [comment]
就是从localhost:3000啊

**Comment by lzxb** [comment]
......看说明啊。修改了代理的服务器就好了https://github.com/lzxb/vue2-demo/blob/master/config/index.js

**Comment by 5265liu** [comment]
这个改成什么比较好啊可以给个例子吗

**Comment by lzxb** [comment]
.......你要连接哪个服务器就填哪个服务器啊，你项目的接口需要请求到哪里，就填写哪里

**Comment by 5265liu** [comment]
我本地的话不填可以吗？我现在就想本地学习下

**Comment by lzxb** [comment]
https://github.com/lzxb/vue2-demo/blob/master/server.js
把代理服务器的去掉就好了

**Comment by 5265liu** [comment]
我把proxy注释l
![qq 20170728172117](https://user-images.githubusercontent.com/19281925/28711301-bc1fdc86-73b9-11e7-8d07-afb07b99aeb2.png)

**Comment by 5265liu** [comment]
不加app只能访问一堆目录

**Comment by 5265liu** [comment]
![image](https://user-images.githubusercontent.com/19281925/28711364-f9ecdffa-73b9-11e7-99c7-0f4118f0becf.png)

**Comment by lzxb** [comment]
https://github.com/lzxb/vue2-demo/blob/master/config/index.js
更改配置不就好了

**Comment by 5265liu** [comment]
不太懂了怎么该啊把那个proxy注释了，index应该不加载了吧我监听的还是3003啊
