### ISSUE TITLE
编译后的文件到底输出到哪里了?

### ISSUE THREAD

**Issue by 03917415** [lzxb/vue2-demo#20]
webpack编译成功, 浏览器中也可以通过[http://localhost:3000/app/#/] 访问.
但是奇怪的是, 怎么也找不到编译后输出的文件.  
配置的不是放到项目目录/app/下, 为什么找不到文件, 浏览器里却可以访问呢?
拜托, 求助!!!

**Comment by lzxb** [comment]
是编译到内存中了

**Comment by 03917415** [comment]
@lzxb ,  非常感谢您的回复!  请教怎么配置生成实体文件, 而不是编译到内存中? 这样很不直观.

**Comment by 03917415** [comment]
哦 , 查了 webpack-dev-server的文档,   了解怎么回事了.  麻烦了!

**Comment by lzxb** [comment]
```bash
npm run dev:dist
```
