### ISSUE TITLE
别名配置后开发环境ok，yarn run build报错

### ISSUE THREAD

**Issue by wukai900610** [lzxb/vue2-demo#23]
`
export const ssr = new SSR({

    name: 'ssr-demo',

    build: {

        alias: {

            '@': path.resolve(__dirname, './src')

        },

        template: path.resolve(__dirname, './index.html')

    }

});
`
别名配置后开发环境ok，yarn run build报错
![image](https://user-images.githubusercontent.com/3339632/85356504-b016b000-b541-11ea-9512-31eb42732891.png)

**Comment by lzxb** [comment]
有代码仓库吗？我拉下来试试。

**Comment by wukai900610** [comment]
> 有代码仓库吗？我拉下来试试。

https://gitee.com/wk365/genesis_demo.git

**Comment by wukai900610** [comment]
> > 有代码仓库吗？我拉下来试试。
> 
> https://gitee.com/wk365/genesis_demo.git

引用别名的文件在app.vue里，大佬帮看下

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/85365378-d1829680-b557-11ea-9235-3bbdbe1f5041.png)

这个是因为把TS编译成js时，相对路径发生了变化。你只需要判断一下当前的配置即可。

**Comment by lzxb** [comment]
`build.sh`修改成下面
```bash
#! /bin/sh
# rm -rf node_modules
# yarn install --registry=https://registry.npm.taobao.org
npm run build:ts
cp index.html ./dist/node
# NODE_ENV=production node dist/node/genesis.build.js
NODE_ENV=production ts-node genesis.build.ts
# rm -rf node_modules
# yarn --prod --registry=https://registry.npm.taobao.org
```

**Comment by lzxb** [comment]
使用TS去编译，就不会出现路径错误的问题。
