### ISSUE TITLE
ie11 ./node_modules/@fmfe/genesis-app/dist/create-app.js 报错语法错误

### ISSUE THREAD

**Issue by wukai900610** [lzxb/vue2-demo#24]
![image](https://user-images.githubusercontent.com/3339632/85987287-08592080-ba20-11ea-9b59-4917a688d901.png)

**Comment by lzxb** [comment]
开发环境，建议使用谷歌浏览器测试，因为没有转成es5。只有生产环境的时候，才会转化成es5

**Comment by wukai900610** [comment]
生产环境也报错
![image](https://user-images.githubusercontent.com/3339632/85990647-eada8580-ba24-11ea-81c4-26df6e94a221.png)

**Comment by lzxb** [comment]
晚点我找个window的电脑测试一下。

**Comment by lzxb** [comment]
你更新一下Genesis到最新版本试试。

**Comment by wukai900610** [comment]
> 你更新一下Genesis到最新版本试试。

更新package.json后生产环境还是不行,大佬你在看下呗
![image](https://user-images.githubusercontent.com/3339632/86985268-742b4e00-c1c3-11ea-901a-bc5a76f16bd3.png)
![image](https://user-images.githubusercontent.com/3339632/86985298-8907e180-c1c3-11ea-869c-731a81a2e7eb.png)

**Comment by wukai900610** [comment]
大佬这项目有空看下呗

**Comment by lzxb** [comment]
晚点我更新最新版本试试。

**Comment by lzxb** [comment]
```ts
import path from 'path';
import { SSR } from '@fmfe/genesis-core';

const ssr = new SSR({
    build: {
        transpile: [path.resolve('node_modules/@fmfe/genesis-app')]
    }
});

```

你试试这种方式

**Comment by lzxb** [comment]
使用最新版本。
