### ISSUE TITLE
这个demo不支持IE浏览器吗，我在非IE浏览器都完美解决了ssr的问题，但在IE下报SCRIPT1002错

### ISSUE THREAD

**Issue by hswgit123** [lzxb/vue2-demo#29]

**Comment by hswgit123** [comment]
可以解决IE的问题吗

**Comment by lzxb** [comment]
IE版本应该要大于>9，demo你可以更新一下最新的依赖看看是否解决。之前有人提过类似的问题。

**Comment by hswgit123** [comment]
我已经使用IE11，安装最新的依赖了，没能解决。类似的问题有解决方法吗[苦涩]
"devDependencies": {
        "@fmfe/genesis-compiler": "0.0.80",
        "@fmfe/genesis-lint": "0.0.80",
        "@types/express": "^4.17.9",
        "@types/node": "^14.14.10",
        "ts-node": "^9.1.0"
    },
    "dependencies": {
        "@fmfe/genesis-app": "0.0.80",
        "@fmfe/genesis-core": "0.0.80",
        "axios": "^0.21.0",
        "body-parser": "^1.19.0",
        "cookie-parser": "^1.4.5",
        "express": "^4.17.1",
        "vue-class-component": "^7.2.6",
        "vue-meta": "^2.4.0",
        "vue-property-decorator": "^9.1.2",
        "vue-router": "^3.4.9",
        "vuex": "^3.6.0"
    },

**Comment by lzxb** [comment]
把错误信息粘贴上来或者截图看看。

**Comment by hswgit123** [comment]
![QQ截图20201207181306](https://user-images.githubusercontent.com/53160474/101338375-d9d94e80-38b7-11eb-9166-6a886714103f.png)

**Comment by lzxb** [comment]
transpile 加上@fmfe/genesis-app试试

**Comment by hswgit123** [comment]
我看demo的genesis.ts文件已经加上了
/**
 * 创建一个 SSR 实例
 */
export const ssr = new SSR({
    build: {
        template: path.resolve(__dirname, './index.html'),
        transpile: [path.resolve('./node_modules/@fmfe/genesis-app/src')]
    }
});

**Comment by lzxb** [comment]
移除 genesis-app 还会报错吗？

**Comment by hswgit123** [comment]
也一样报错，我另外使用genesis试着建了个demo，貌似当页面有数据请求的时候，IE渲染的代码就报错，chrome内核浏览器都没问题，单单一些html标签是正当显示的

**Comment by lzxb** [comment]
目前来看，IE确实无解了。只能放弃。
