### ISSUE TITLE
请问vsCode ，es2016语法提示报错问题

### ISSUE THREAD

**Issue by nbin2008** [lzxb/vue2-demo#3]
clone项目下来，用的是vsCode编辑器，于是我也下了，很好用，有个小问题请教下。

let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };

主要是...这种，vsCode会提示报错（在.js文件中），找了很久没有找到解决办法，求指导呀

**Comment by lzxb** [comment]
我也是遇到这个问题，所以在js文件中，我一般都是使用Object.assign方法，vue中可以使用拓展晕算法。

**Comment by nbin2008** [comment]
这样的，谢谢

**Comment by lzxb** [comment]
只能等vs code升级支持拓展运算符了，不然你就只能忍着警告信息了

**Comment by bailicangdu** [comment]
十分感谢🙏
