### ISSUE TITLE
项目拉下来无法运行需要添加@babel/plugin-proposal-optional-chaining支持

### ISSUE THREAD

**Issue by iceshu** [lzxb/vue2-demo#30]
如题，项目用了ts 的 ？。的方法去做 但是没有支持的插件

![image](https://user-images.githubusercontent.com/6309056/109095003-e605d700-7755-11eb-946a-1c2b6bf350c8.png)

所以需要在
genesis.ts 里 webpackchai增加下支持
```javascript
class ChainingPlugin extends Plugin {
    /**
     * 修改webpack的配置
     */
    public chainWebpack({ config }: WebpackHookParams) {
        config.module
            .rule("ts")
            .test(/\.(t)sx?$/)
            .use("babel")
            .loader("babel-loader")
            .tap(options => {
                const { plugins } = options;
                plugins.push(["@babel/plugin-proposal-optional-chaining"]);
                options.plugins = plugins;
                return options;
            })
            .end();
    }
}

//这里增加下刚写的
ssr.plugin.use(new ChainingWebpack(ssr));
```

**Comment by JWong1105** [comment]
> ```js
> WebpackHookParams
> ```

你好，能贴出完整的修改代码吗？WebpackHookParams 报错了

**Comment by lzxb** [comment]
这个是`@babel/preset-env`的bug导致的。它没有根据当前node的版本号，来引入对应的插件。
你的node的版本号多少？

**Comment by lzxb** [comment]
你可以看下这个配置:
https://fmfe.github.io/genesis-docs/core/#build-browsers
修改一下node的版本号，降低一些，比如我使用12.6就不会有这个问题。

**Comment by JWong1105** [comment]
> 你可以看下这个配置:
> https://fmfe.github.io/genesis-docs/core/#build-browsers
> 修改一下node的版本号，降低一些，比如我使用12.6就不会有这个问题。

谢谢，我版本比较新 v14.15.4

**Comment by JWong1105** [comment]
OK 了，node 切换到 12.1.0，正常运行（12.0.0只支持32位系统）

**Comment by lzxb** [comment]
奈斯。

**Comment by iceshu** [comment]
@JWong1105 
这里引用的 我的node版本v14.15.1
```javascript
import { SSR, Renderer, Plugin, WebpackHookParams } from "@fmfe/genesis-core";
```

**Comment by JWong1105** [comment]
@iceshu 
我在试高版本的 node(14.15.4)
ssr.plugin.use(new ChainingWebpack(ssr));
"ChainingWebpack" 这个类试在哪定义或导入的呢

**Comment by lzxb** [comment]
你可以看下这个文档：
https://fmfe.github.io/genesis-docs/guide/webpack.html#%E5%AE%98%E6%96%B9%E5%86%85%E7%BD%AE%E7%9A%84-webpack-%E6%8F%92%E4%BB%B6

**Comment by JWong1105** [comment]
@lzxb 谢谢，@iceshu 应该是敲错了名字，ssr.plugin.use(new ChainingPlugin(ssr));
