### ISSUE TITLE
npm run dev 创建代理 不能访问项目

### ISSUE THREAD

**Issue by lirui0081** [lzxb/vue2-demo#4]
npm install 
npm run dev 后 提示
```
node server
[HPM] Proxy crated: **  ->  https://cnodejs.org/
http://localhost:3000/app
```
打开localhost地址后显示的是 cnodejs.org的页面？

**Comment by lzxb** [comment]
项目的访问地址是：http://localhost:3000/app/
 https://cnodejs.org/的页面，是因为代理了这个网站
