### ISSUE TITLE
有个问题想请教下 

### ISSUE THREAD

**Issue by huangzhenxian** [lzxb/vue2-demo#6]
![image](https://cloud.githubusercontent.com/assets/8416974/21096747/1c166f5a-c09c-11e6-9db9-d935d36444b9.png)
你这里为什么要用这种方式   

用dispatch 不是更好吗  例如
this.$store.dispatch(USER_SIGN_IN,this.form);
this.$router.push('idx');

**Comment by lzxb** [comment]
其实都可以，我使用这种只是预防以后此方法需要在多个地方使用的时候，能精简代码，或者说只需要维护一份代码

**Comment by huangzhenxian** [comment]
嗯谢谢
